from collections import OrderedDict
from decimal import Decimal
from pyspark.sql.types import (
    IntegerType, LongType, StringType,
    DecimalType, DateType, TimestampType, DoubleType, BooleanType,
)


# Map simplified SQL types to Python type checks
TYPE_CHECKS = {
    "BIGINT": lambda v: isinstance(v, int),
    "INT": lambda v: isinstance(v, int),
    "DECIMAL": lambda v: isinstance(v, (Decimal, float, int)),  # Arrow may materialize decimals as Decimal or float
    "VARCHAR": lambda v: isinstance(v, str),
    "DATE": lambda v: hasattr(v, "year") and hasattr(v, "month") and hasattr(v, "day"),  # datetime.date
    "TIMESTAMP": lambda v: hasattr(v, "year") and hasattr(v, "hour"),  # datetime-like
    "DOUBLE": lambda v: isinstance(v, float),
    "BOOLEAN": lambda v: isinstance(v, bool) or v is None,
}


TABLES_METADATA = {
    "nation": OrderedDict([
        ("n_nationkey", {"type": "BIGINT", "nullable": False, "spark": LongType}),
        ("n_name", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("n_regionkey", {"type": "INT", "nullable": False, "spark": IntegerType}),
        ("n_comment", {"type": "VARCHAR", "nullable": True, "spark": StringType}),  # nullable for coverage
    ]),
    "region": OrderedDict([
        ("r_regionkey", {"type": "INT", "nullable": False, "spark": IntegerType}),
        ("r_name", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("r_comment", {"type": "VARCHAR", "nullable": True, "spark": StringType}),
    ]),
    "supplier": OrderedDict([
        ("s_suppkey", {"type": "BIGINT", "nullable": False, "spark": LongType}),
        ("s_name", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("s_address", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("s_nationkey", {"type": "INT", "nullable": False, "spark": IntegerType}),
        ("s_phone", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("s_acctbal", {"type": "DECIMAL(15,2)", "nullable": False, "spark": lambda: DecimalType(15, 2)}),
        ("s_comment", {"type": "VARCHAR", "nullable": True, "spark": StringType}),
    ]),
    "part": OrderedDict([
        ("p_partkey", {"type": "BIGINT", "nullable": False, "spark": LongType}),
        ("p_name", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("p_mfgr", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("p_brand", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("p_type", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("p_size", {"type": "INT", "nullable": False, "spark": IntegerType}),
        ("p_container", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("p_retailprice", {"type": "DECIMAL(15,2)", "nullable": False, "spark": lambda: DecimalType(15, 2)}),
        ("p_comment", {"type": "VARCHAR", "nullable": True, "spark": StringType}),
    ]),
    "partsupp": OrderedDict([
        ("ps_partkey", {"type": "BIGINT", "nullable": False, "spark": LongType}),
        ("ps_suppkey", {"type": "BIGINT", "nullable": False, "spark": LongType}),
        ("ps_availqty", {"type": "BIGINT", "nullable": False, "spark": LongType}),
        ("ps_supplycost", {"type": "DECIMAL(15,2)", "nullable": False, "spark": lambda: DecimalType(15, 2)}),
        ("ps_comment", {"type": "VARCHAR", "nullable": True, "spark": StringType}),
    ]),
    "customer": OrderedDict([
        ("c_custkey", {"type": "BIGINT", "nullable": False, "spark": LongType}),
        ("c_name", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("c_address", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("c_nationkey", {"type": "INT", "nullable": False, "spark": IntegerType}),
        ("c_phone", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("c_acctbal", {"type": "DECIMAL(15,2)", "nullable": False, "spark": lambda: DecimalType(15, 2)}),
        ("c_mktsegment", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("c_comment", {"type": "VARCHAR", "nullable": True, "spark": StringType}),
    ]),
    "orders": OrderedDict([
        ("o_orderkey", {"type": "BIGINT", "nullable": False, "spark": LongType}),
        ("o_custkey", {"type": "BIGINT", "nullable": False, "spark": LongType}),
        ("o_orderstatus", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("o_totalprice", {"type": "DECIMAL(15,2)", "nullable": False, "spark": lambda: DecimalType(15, 2)}),
        ("o_orderdate", {"type": "DATE", "nullable": False, "spark": DateType}),
        ("o_orderpriority", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("o_clerk", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("o_shippriority", {"type": "INT", "nullable": False, "spark": IntegerType}),
        ("o_comment", {"type": "VARCHAR", "nullable": True, "spark": StringType}),
    ]),
    "lineitem": OrderedDict([
        ("l_orderkey", {"type": "BIGINT", "nullable": False, "spark": LongType}),
        ("l_partkey", {"type": "BIGINT", "nullable": False, "spark": LongType}),
        ("l_suppkey", {"type": "BIGINT", "nullable": False, "spark": LongType}),
        ("l_linenumber", {"type": "BIGINT", "nullable": False, "spark": LongType}),
        ("l_quantity", {"type": "DECIMAL(15,2)", "nullable": False, "spark": lambda: DecimalType(15, 2)}),
        ("l_extendedprice", {"type": "DECIMAL(15,2)", "nullable": False, "spark": lambda: DecimalType(15, 2)}),
        ("l_discount", {"type": "DECIMAL(15,2)", "nullable": False, "spark": lambda: DecimalType(15, 2)}),
        ("l_tax", {"type": "DECIMAL(15,2)", "nullable": False, "spark": lambda: DecimalType(15, 2)}),
        ("l_returnflag", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("l_linestatus", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("l_shipdate", {"type": "DATE", "nullable": False, "spark": DateType}),
        ("l_commitdate", {"type": "DATE", "nullable": False, "spark": DateType}),
        ("l_receiptdate", {"type": "DATE", "nullable": False, "spark": DateType}),
        ("l_shipinstruct", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("l_shipmode", {"type": "VARCHAR", "nullable": False, "spark": StringType}),
        ("l_comment", {"type": "VARCHAR", "nullable": True, "spark": StringType}),
    ]),
    "edge_cases_test": OrderedDict([
        ("pk", {"type": "BIGINT", "nullable": False, "spark": LongType}),
        ("large_int", {"type": "BIGINT", "nullable": True, "spark": LongType}),
        ("negative_int", {"type": "INT", "nullable": True, "spark": IntegerType}),
        ("high_precision_dec", {"type": "DECIMAL(38,18)", "nullable": True, "spark": lambda: DecimalType(38, 18)}),
        ("zero_dec", {"type": "DECIMAL(5,2)", "nullable": True, "spark": lambda: DecimalType(5, 2)}),
        ("empty_string", {"type": "VARCHAR", "nullable": True, "spark": StringType}),
        ("unicode_string", {"type": "VARCHAR", "nullable": True, "spark": StringType}),
        ("timestamp_min", {"type": "TIMESTAMP", "nullable": True, "spark": TimestampType}),
        ("timestamp_max", {"type": "TIMESTAMP", "nullable": True, "spark": TimestampType}),
        ("bool_true", {"type": "BOOLEAN", "nullable": True, "spark": BooleanType}),
        ("bool_null", {"type": "BOOLEAN", "nullable": True, "spark": BooleanType}),
        ("floating_nan", {"type": "DOUBLE", "nullable": True, "spark": DoubleType}),
        ("floating_inf", {"type": "DOUBLE", "nullable": True, "spark": DoubleType}),
])
}

TPC_H_INSERTION_DATA = {
    "region": [
        {"r_regionkey": 1, "r_name": "EUROPE", "r_comment": "Region comment"},
        {"r_regionkey": 2, "r_name": "AMERICA", "r_comment": "Region comment"},
        {"r_regionkey": 3, "r_name": "ASIA", "r_comment": "Region comment"}
    ],
    "nation": [
        {"n_nationkey": 1, "n_name": "FRANCE", "n_regionkey": 1, "n_comment": "Nation comment"},
        {"n_nationkey": 2, "n_name": "GERMANY", "n_regionkey": 1, "n_comment": "Nation comment"},
        {"n_nationkey": 3, "n_name": "CANADA", "n_regionkey": 2, "n_comment": "Nation comment"},
        {"n_nationkey": 4, "n_name": "BRAZIL", "n_regionkey": 2, "n_comment": "Nation comment"},
        {"n_nationkey": 5, "n_name": "SAUDI ARABIA", "n_regionkey": 3, "n_comment": "Nation comment"}
    ],
    "supplier": [
        {"s_suppkey": 1, "s_name": "Supplier#1", "s_address": "Address",
         "s_nationkey": 1, "s_phone": "123-456-7890", "s_acctbal": Decimal("1000.00"),
         "s_comment": ""},
        {"s_suppkey": 2, "s_name": "Supplier#2", "s_address": "Address",
         "s_nationkey": 2, "s_phone": "123-456-7890", "s_acctbal": Decimal("2000.00"),
         "s_comment": ""},
        {"s_suppkey": 3, "s_name": "Supplier#3", "s_address": "Address",
         "s_nationkey": 3, "s_phone": "123-456-7890", "s_acctbal": Decimal("3000.00"),
         "s_comment": "Customer Complaints"},
        {"s_suppkey": 4, "s_name": "Supplier#4", "s_address": "Address",
         "s_nationkey": 5, "s_phone": "123-456-7890", "s_acctbal": Decimal("4000.00"),
         "s_comment": ""}
    ],
    "customer": [
        {"c_custkey": 1, "c_name": "Customer#1", "c_address": "Address",
         "c_nationkey": 1, "c_phone": "13-123-4567", "c_acctbal": Decimal("1000.00"),
         "c_mktsegment": "BUILDING", "c_comment": ""},
        {"c_custkey": 2, "c_name": "Customer#2", "c_address": "Address",
         "c_nationkey": 2, "c_phone": "31-123-4567", "c_acctbal": Decimal("2000.00"),
         "c_mktsegment": "HOUSEHOLD", "c_comment": ""},
        {"c_custkey": 3, "c_name": "Customer#3", "c_address": "Address",
         "c_nationkey": 4, "c_phone": "23-123-4567", "c_acctbal": Decimal("3000.00"),
         "c_mktsegment": "BUILDING", "c_comment": ""},
        {"c_custkey": 101, "c_name": "Asian Customer", "c_address": "Address",
         "c_nationkey": 5, "c_phone": "18-123-4567", "c_acctbal": Decimal("5000.00"),
         "c_mktsegment": "AUTOMOBILE", "c_comment": ""},
        {"c_custkey": 102, "c_name": "NoOrder Customer", "c_address": "Address",
         "c_nationkey": 2, "c_phone": "31-999-9999", "c_acctbal": Decimal("9000.00"),
         "c_mktsegment": "FURNITURE", "c_comment": ""}
    ],
    "part": [
        {"p_partkey": 1, "p_name": "green part", "p_mfgr": "Manufacturer#1",
         "p_brand": "Brand#12", "p_type": "SMALL PLATED BRASS", "p_size": 15,
         "p_container": "SM CASE", "p_retailprice": Decimal("100.00"), "p_comment": ""},
        {"p_partkey": 2, "p_name": "blue part", "p_mfgr": "Manufacturer#2",
         "p_brand": "Brand#23", "p_type": "MEDIUM POLISHED COPPER", "p_size": 14,
         "p_container": "MED BOX", "p_retailprice": Decimal("200.00"), "p_comment": ""},
        {"p_partkey": 3, "p_name": "forest green part", "p_mfgr": "Manufacturer#3",
         "p_brand": "Brand#34", "p_type": "ECONOMY ANODIZED STEEL", "p_size": 9,
         "p_container": "LG PKG", "p_retailprice": Decimal("300.00"), "p_comment": ""},
        {"p_partkey": 101, "p_name": "Promo Part", "p_mfgr": "Manufacturer#1",
         "p_brand": "Brand#12", "p_type": "PROMO BRUSHED TIN", "p_size": 10,
         "p_container": "SM PKG", "p_retailprice": Decimal("150.00"), "p_comment": ""},
        {"p_partkey": 102, "p_name": "Specific Brand Part", "p_mfgr": "Manufacturer#2",
         "p_brand": "Brand#12", "p_type": "STANDARD BURNISHED STEEL", "p_size": 4,
         "p_container": "SM PACK", "p_retailprice": Decimal("250.00"), "p_comment": ""}
    ],
    "partsupp": [
        {"ps_partkey": 1, "ps_suppkey": 1, "ps_availqty": 1000,
         "ps_supplycost": Decimal("10.00"), "ps_comment": ""},
        {"ps_partkey": 1, "ps_suppkey": 2, "ps_availqty": 2000,
         "ps_supplycost": Decimal("11.00"), "ps_comment": ""},
        {"ps_partkey": 2, "ps_suppkey": 2, "ps_availqty": 1500,
         "ps_supplycost": Decimal("12.00"), "ps_comment": ""},
        {"ps_partkey": 3, "ps_suppkey": 3, "ps_availqty": 2500,
         "ps_supplycost": Decimal("13.00"), "ps_comment": ""},
        {"ps_partkey": 3, "ps_suppkey": 4, "ps_availqty": 800,
         "ps_supplycost": Decimal("14.00"), "ps_comment": ""},
        {"ps_partkey": 101, "ps_suppkey": 1, "ps_availqty": 100,
         "ps_supplycost": Decimal("15.00"), "ps_comment": ""},
        {"ps_partkey": 102, "ps_suppkey": 1, "ps_availqty": 200,
         "ps_supplycost": Decimal("25.00"), "ps_comment": ""}
    ],
    "orders": [
        {"o_orderkey": 1, "o_custkey": 1, "o_orderstatus": "F",
         "o_totalprice": Decimal("1000.00"), "o_orderdate": "1994-01-15",
         "o_orderpriority": "1-URGENT", "o_clerk": "Clerk#1",
         "o_shippriority": 0, "o_comment": ""},
        {"o_orderkey": 2, "o_custkey": 1, "o_orderstatus": "O",
         "o_totalprice": Decimal("2000.00"), "o_orderdate": "1995-02-20",
         "o_orderpriority": "2-HIGH", "o_clerk": "Clerk#2",
         "o_shippriority": 1, "o_comment": ""},
        {"o_orderkey": 3, "o_custkey": 3, "o_orderstatus": "F",
         "o_totalprice": Decimal("3000.00"), "o_orderdate": "1993-08-01",
         "o_orderpriority": "5-LOW", "o_clerk": "Clerk#3",
         "o_shippriority": 0, "o_comment": "special requests"},
        {"o_orderkey": 101, "o_custkey": 101, "o_orderstatus": "F",
         "o_totalprice": Decimal("500.00"), "o_orderdate": "1994-06-01",
         "o_orderpriority": "3-MEDIUM", "o_clerk": "Clerk#100",
         "o_shippriority": 0, "o_comment": ""},
        {"o_orderkey": 102, "o_custkey": 1, "o_orderstatus": "F",
         "o_totalprice": Decimal("600.00"), "o_orderdate": "1995-09-01",
         "o_orderpriority": "3-MEDIUM", "o_clerk": "Clerk#101",
         "o_shippriority": 0, "o_comment": ""},
        {"o_orderkey": 103, "o_custkey": 3, "o_orderstatus": "F",
         "o_totalprice": Decimal("700.00"), "o_orderdate": "1995-11-11",
         "o_orderpriority": "3-MEDIUM", "o_clerk": "Clerk#102",
         "o_shippriority": 0, "o_comment": ""},
        {"o_orderkey": 104, "o_custkey": 1, "o_orderstatus": "F",
         "o_totalprice": Decimal("800.00"), "o_orderdate": "1995-08-20",
         "o_orderpriority": "3-MEDIUM", "o_clerk": "Clerk#103",
         "o_shippriority": 0, "o_comment": ""},
        {"o_orderkey": 105, "o_custkey": 2, "o_orderstatus": "F",
         "o_totalprice": Decimal("900.00"), "o_orderdate": "1996-01-10",
         "o_orderpriority": "3-MEDIUM", "o_clerk": "Clerk#104",
         "o_shippriority": 0, "o_comment": ""},
        {"o_orderkey": 106, "o_custkey": 2, "o_orderstatus": "F",
         "o_totalprice": Decimal("1000.00"), "o_orderdate": "1995-01-01",
         "o_orderpriority": "3-MEDIUM", "o_clerk": "Clerk#105",
         "o_shippriority": 0, "o_comment": ""},
        {"o_orderkey": 107, "o_custkey": 2, "o_orderstatus": "F",
         "o_totalprice": Decimal("50.00"), "o_orderdate": "1995-01-02",
         "o_orderpriority": "3-MEDIUM", "o_clerk": "Clerk#106",
         "o_shippriority": 0, "o_comment": ""},
        {"o_orderkey": 108, "o_custkey": 1, "o_orderstatus": "F",
         "o_totalprice": Decimal("10000.00"), "o_orderdate": "1995-01-03",
         "o_orderpriority": "3-MEDIUM", "o_clerk": "Clerk#107",
         "o_shippriority": 0, "o_comment": ""},
        {"o_orderkey": 109, "o_custkey": 1, "o_orderstatus": "F",
         "o_totalprice": Decimal("1100.00"), "o_orderdate": "1995-01-04",
         "o_orderpriority": "3-MEDIUM", "o_clerk": "Clerk#108",
         "o_shippriority": 0, "o_comment": ""},
        {"o_orderkey": 110, "o_custkey": 3, "o_orderstatus": "F",
         "o_totalprice": Decimal("1200.00"), "o_orderdate": "1994-05-05",
         "o_orderpriority": "3-MEDIUM", "o_clerk": "Clerk#109",
         "o_shippriority": 0, "o_comment": ""},
        {"o_orderkey": 111, "o_custkey": 1, "o_orderstatus": "F",
         "o_totalprice": Decimal("1300.00"), "o_orderdate": "1995-01-05",
         "o_orderpriority": "3-MEDIUM", "o_clerk": "Clerk#110",
         "o_shippriority": 0, "o_comment": ""}
    ],
    "lineitem": [
        {"l_orderkey": 1, "l_partkey": 1, "l_suppkey": 1, "l_linenumber": 1,
         "l_quantity": Decimal("10.00"), "l_extendedprice": Decimal("1000.00"),
         "l_discount": Decimal("0.05"), "l_tax": Decimal("0.08"),
         "l_returnflag": "N", "l_linestatus": "O",
         "l_shipdate": "1997-08-01", "l_commitdate": "1997-09-01",
         "l_receiptdate": "1997-09-20", "l_shipinstruct": "DELIVER IN PERSON",
         "l_shipmode": "MAIL", "l_comment": ""},
        {"l_orderkey": 2, "l_partkey": 2, "l_suppkey": 2, "l_linenumber": 1,
         "l_quantity": Decimal("20.00"), "l_extendedprice": Decimal("2000.00"),
         "l_discount": Decimal("0.06"), "l_tax": Decimal("0.07"),
         "l_returnflag": "R", "l_linestatus": "F",
         "l_shipdate": "1994-02-15", "l_commitdate": "1994-03-10",
         "l_receiptdate": "1994-03-15", "l_shipinstruct": "DELIVER IN PERSON",
         "l_shipmode": "SHIP", "l_comment": ""},
        {"l_orderkey": 2, "l_partkey": 3, "l_suppkey": 3, "l_linenumber": 2,
         "l_quantity": Decimal("15.00"), "l_extendedprice": Decimal("1500.00"),
         "l_discount": Decimal("0.06"), "l_tax": Decimal("0.07"),
         "l_returnflag": "R", "l_linestatus": "F",
         "l_shipdate": "1994-03-20", "l_commitdate": "1994-04-01",
         "l_receiptdate": "1994-04-15", "l_shipinstruct": "TAKE BACK RETURN",
         "l_shipmode": "REG AIR", "l_comment": ""},
        {"l_orderkey": 3, "l_partkey": 3, "l_suppkey": 4, "l_linenumber": 1,
         "l_quantity": Decimal("25.00"), "l_extendedprice": Decimal("2500.00"),
         "l_discount": Decimal("0.04"), "l_tax": Decimal("0.08"),
         "l_returnflag": "A", "l_linestatus": "F",
         "l_shipdate": "1995-04-01", "l_commitdate": "1995-04-20",
         "l_receiptdate": "1995-04-25", "l_shipinstruct": "NONE",
         "l_shipmode": "AIR", "l_comment": ""},
        {"l_orderkey": 101, "l_partkey": 3, "l_suppkey": 4, "l_linenumber": 1,
         "l_quantity": Decimal("1.00"), "l_extendedprice": Decimal("500.00"),
         "l_discount": Decimal("0.0"), "l_tax": Decimal("0.08"),
         "l_returnflag": "N", "l_linestatus": "F",
         "l_shipdate": "1994-07-01", "l_commitdate": "1994-08-01",
         "l_receiptdate": "1994-08-10", "l_shipinstruct": "NONE",
         "l_shipmode": "AIR", "l_comment": ""},
        {"l_orderkey": 102, "l_partkey": 1, "l_suppkey": 2, "l_linenumber": 1,
         "l_quantity": Decimal("2.00"), "l_extendedprice": Decimal("600.00"),
         "l_discount": Decimal("0.0"), "l_tax": Decimal("0.08"),
         "l_returnflag": "N", "l_linestatus": "F",
         "l_shipdate": "1995-10-10", "l_commitdate": "1995-11-01",
         "l_receiptdate": "1995-11-10", "l_shipinstruct": "NONE",
         "l_shipmode": "AIR", "l_comment": ""},
        {"l_orderkey": 103, "l_partkey": 3, "l_suppkey": 3, "l_linenumber": 1,
         "l_quantity": Decimal("3.00"), "l_extendedprice": Decimal("700.00"),
         "l_discount": Decimal("0.0"), "l_tax": Decimal("0.08"),
         "l_returnflag": "N", "l_linestatus": "F",
         "l_shipdate": "1995-12-01", "l_commitdate": "1995-12-20",
         "l_receiptdate": "1995-12-30", "l_shipinstruct": "NONE",
         "l_shipmode": "AIR", "l_comment": ""},
        {"l_orderkey": 104, "l_partkey": 101, "l_suppkey": 1, "l_linenumber": 1,
         "l_quantity": Decimal("4.00"), "l_extendedprice": Decimal("800.00"),
         "l_discount": Decimal("0.1"), "l_tax": Decimal("0.08"),
         "l_returnflag": "N", "l_linestatus": "F",
         "l_shipdate": "1995-09-15", "l_commitdate": "1995-10-01",
         "l_receiptdate": "1995-10-10", "l_shipinstruct": "NONE",
         "l_shipmode": "AIR", "l_comment": ""},
        {"l_orderkey": 105, "l_partkey": 1, "l_suppkey": 1, "l_linenumber": 1,
         "l_quantity": Decimal("5.00"), "l_extendedprice": Decimal("900.00"),
         "l_discount": Decimal("0.0"), "l_tax": Decimal("0.08"),
         "l_returnflag": "N", "l_linestatus": "F",
         "l_shipdate": "1996-02-01", "l_commitdate": "1996-03-01",
         "l_receiptdate": "1996-03-10", "l_shipinstruct": "NONE",
         "l_shipmode": "AIR", "l_comment": ""},
        {"l_orderkey": 106, "l_partkey": 2, "l_suppkey": 2, "l_linenumber": 1,
         "l_quantity": Decimal("100.00"), "l_extendedprice": Decimal("1000.00"),
         "l_discount": Decimal("0.05"), "l_tax": Decimal("0.08"),
         "l_returnflag": "N", "l_linestatus": "F",
         "l_shipdate": "1995-02-01", "l_commitdate": "1995-03-01",
         "l_receiptdate": "1995-03-10", "l_shipinstruct": "NONE",
         "l_shipmode": "SHIP", "l_comment": ""},
        {"l_orderkey": 107, "l_partkey": 2, "l_suppkey": 2, "l_linenumber": 1,
         "l_quantity": Decimal("1.00"), "l_extendedprice": Decimal("50.00"),
         "l_discount": Decimal("0.05"), "l_tax": Decimal("0.08"),
         "l_returnflag": "N", "l_linestatus": "F",
         "l_shipdate": "1995-02-02", "l_commitdate": "1995-03-02",
         "l_receiptdate": "1995-03-11", "l_shipinstruct": "NONE",
         "l_shipmode": "SHIP", "l_comment": ""},
        {"l_orderkey": 108, "l_partkey": 1, "l_suppkey": 1, "l_linenumber": 1,
         "l_quantity": Decimal("200.00"), "l_extendedprice": Decimal("5000.00"),
         "l_discount": Decimal("0.05"), "l_tax": Decimal("0.08"),
         "l_returnflag": "N", "l_linestatus": "F",
         "l_shipdate": "1995-02-03", "l_commitdate": "1995-03-03",
         "l_receiptdate": "1995-03-12", "l_shipinstruct": "NONE",
         "l_shipmode": "MAIL", "l_comment": ""},
        {"l_orderkey": 108, "l_partkey": 2, "l_suppkey": 2, "l_linenumber": 2,
         "l_quantity": Decimal("150.00"), "l_extendedprice": Decimal("5000.00"),
         "l_discount": Decimal("0.05"), "l_tax": Decimal("0.08"),
         "l_returnflag": "N", "l_linestatus": "F",
         "l_shipdate": "1995-02-03", "l_commitdate": "1995-03-03",
         "l_receiptdate": "1995-03-12", "l_shipinstruct": "NONE",
         "l_shipmode": "MAIL", "l_comment": ""},
        {"l_orderkey": 109, "l_partkey": 102, "l_suppkey": 1, "l_linenumber": 1,
         "l_quantity": Decimal("5.00"), "l_extendedprice": Decimal("1100.00"),
         "l_discount": Decimal("0.05"), "l_tax": Decimal("0.08"),
         "l_returnflag": "N", "l_linestatus": "F",
         "l_shipdate": "1995-02-04", "l_commitdate": "1995-03-04",
         "l_receiptdate": "1995-03-13", "l_shipinstruct": "DELIVER IN PERSON",
         "l_shipmode": "AIR", "l_comment": ""},
        {"l_orderkey": 110, "l_partkey": 3, "l_suppkey": 3, "l_linenumber": 1,
         "l_quantity": Decimal("10.00"), "l_extendedprice": Decimal("1200.00"),
         "l_discount": Decimal("0.05"), "l_tax": Decimal("0.08"),
         "l_returnflag": "N", "l_linestatus": "F",
         "l_shipdate": "1994-06-01", "l_commitdate": "1994-07-01",
         "l_receiptdate": "1994-07-10", "l_shipinstruct": "NONE",
         "l_shipmode": "AIR", "l_comment": ""},
        {"l_orderkey": 111, "l_partkey": 3, "l_suppkey": 4, "l_linenumber": 1,
         "l_quantity": Decimal("10.00"), "l_extendedprice": Decimal("650.00"),
         "l_discount": Decimal("0.05"), "l_tax": Decimal("0.08"),
         "l_returnflag": "N", "l_linestatus": "F",
         "l_shipdate": "1995-02-05", "l_commitdate": "1995-03-01",
         "l_receiptdate": "1995-03-10", "l_shipinstruct": "NONE",
         "l_shipmode": "SHIP", "l_comment": ""},
        {"l_orderkey": 111, "l_partkey": 1, "l_suppkey": 1, "l_linenumber": 2,
         "l_quantity": Decimal("10.00"), "l_extendedprice": Decimal("650.00"),
         "l_discount": Decimal("0.05"), "l_tax": Decimal("0.08"),
         "l_returnflag": "N", "l_linestatus": "F",
         "l_shipdate": "1995-02-05", "l_commitdate": "1995-03-10",
         "l_receiptdate": "1995-03-05", "l_shipinstruct": "NONE",
         "l_shipmode": "SHIP", "l_comment": ""}
    ]
}

EDGE_CASES_VALUES = {
        "pk": 1,
        "large_int": 2 ** 60,
        "negative_int": -1,
        "high_precision_dec": "0.12345678901234568",
        "zero_dec": "0.00",
        "empty_string": "",
        "unicode_string": "𝔘𝔫𝔦𝔠𝔬𝔡𝔢✓",
        "timestamp_min": "1970-01-01T00:00:00",
        "timestamp_max": "9999-12-31T23:59:59",
        "bool_true": True,
        "bool_null": None,
        "floating_nan": float("nan"),
        "floating_inf": float("inf"),
    }