/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */
import type { OrderDirection } from './orderDirection';

export type GetSchemasParams = {
  /**
   * Schemas offset
   * @minimum 0
   */
  offset?: number;
  /**
   * Schemas limit
   * @minimum 0
   */
  limit?: number;
  /**
   * Schemas search
   */
  search?: string;
  /**
   * Order by: schema_name (default), database_name, created_at, updated_at
   */
  order_by?: string;
  /**
   * Order direction: ASC, DESC (default)
   */
  order_direction?: OrderDirection;
};
