/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */

export type GetTablePreviewDataParams = {
  /**
   * Table preview offset
   * @minimum 0
   */
  offset?: number;
  /**
   * Table preview limit
   * @minimum 0
   */
  limit?: number;
};
