/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */

export type UploadFileParams = {
  /**
   * Has header
   */
  header?: boolean;
  /**
   * an optional column delimiter, defaults to comma `','`
   * @minimum 0
   */
  delimiter?: number;
  /**
   * an escape character
   * @minimum 0
   */
  escape?: number;
  /**
   * a custom quote character, defaults to double quote `'"'`
   * @minimum 0
   */
  quote?: number;
  /**
   * a custom terminator character, defaults to CRLF
   * @minimum 0
   */
  terminator?: number;
  /**
   * a comment character
   * @minimum 0
   */
  comment?: number;
};
