name: Patchdog
#Best resort is calling patchdog once, when last commit is pushed into HEAD branch
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
  pull_request: 

env:
  CARGO_TERM_COLOR: always

jobs:
  run_patchdog:
    if: |
      github.event_name == 'pull_request' &&
      (
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@patchdog')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@patchdog'))
      ) 


    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write

    steps:
      - name: Patchdog
        uses: YuraLitvinov/patchdog@v1.2.50
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          api_key_gemini: ${{ secrets.API_KEY_GEMINI }}
